
version: '3'

services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=admin
      - POSTGRES_DB=balden_hospital
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web-app:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  postgres_data:
