
version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  auth-service:
    image: authservice:1.0
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
  
  frontend:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  mongodb_data:
