
version: '3'

services:
  redis-cache:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  api-service:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start

  patient-portal:
    image: nginx:alpine
    ports:
      - "8000:80"
